// <auto-generated />
namespace Net.Application.Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_some_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_some_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201611162347448_add_some_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
