// <auto-generated />
namespace Net.Application.Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class adjustorderitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustorderitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201612180756059_adjust order item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
