// <auto-generated />
namespace Net.Application.Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class adjust_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjust_order));
        
        string IMigrationMetadata.Id
        {
            get { return "201612241419255_adjust_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
